services:
  - type: web
    name: jamaicahealthops-api
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    envVars:
      - key: DS_DATA_PATH
        value: /app/data

  - type: web
    name: jamaicahealthops-ui
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free